sudo: required
services:
  - docker

before_install:
  - docker build -t jrrlokken/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jrrlokken/react-test npm test -- --coverage

after_success:
  - docker build -t jrrlokken/multi-client ./client
  - docker build -t jrrlokken/multi-nginx ./nginx
  - docker build -t jrrlokken/multi-server ./server
  - docker build -t jrrlokken/multi-worker ./worker

  # Login to the docker CLI and push our images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jrrlokken/multi-client
  - docker push jrrlokken/multi-nginx
  - docker push jrrlokken/multi-server
  - docker push jrrlokken/multi-worker
